export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_FAIL';
export const LOGIN_FAIL = 'LOGIN_SUCCESS';
export const AUTH_LOADING = 'AUTH_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const FETCHING_ACCOUNTS = 'FETCHING_ACCOUNTS';
export const ACCOUNTS_FETCHED = 'ACCOUNTS_FETCHED';
export const ACCOUNT_FETCH_FAILED = 'ACCOUNT_FETCH_FAILED';
export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS';